v1/config/routes.rb
Rails.application.routes.draw do
  resources :user_article_views
  resources :bookmarks
  resources :summaries
  resources :users
  resources :articles

  root "home#index"

end

v1/app/controllers/user_article_views_controller.rb
class UserArticleViewsController < ApplicationController
  # before_action :set_user_article_view, only: [:show, :edit, :update, :destroy]

  # GET /user_article_views
  # GET /user_article_views.json
  def index
    @user_article_views = UserArticleView.all
  end

  # GET /user_article_views/1
  # GET /user_article_views/1.json
  def show
  end

  # GET /user_article_views/new
  def new
    @user_article_view = UserArticleView.new
  end

  # GET /user_article_views/1/edit
  def edit
  end

  # POST /user_article_views
  # POST /user_article_views.json
  def create
    @user_article_view = UserArticleView.new(user_article_view_params)

    respond_to do |format|
      if @user_article_view.save
        format.html { redirect_to @user_article_view, notice: 'User article view was successfully created.' }
        format.json { render :show, status: :created, location: @user_article_view }
      else
        format.html { render :new }
        format.json { render json: @user_article_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_article_views/1
  # PATCH/PUT /user_article_views/1.json
  def update
    respond_to do |format|
      if @user_article_view.update(user_article_view_params)
        format.html { redirect_to @user_article_view, notice: 'User article view was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_article_view }
      else
        format.html { render :edit }
        format.json { render json: @user_article_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_article_views/1
  # DELETE /user_article_views/1.json
  def destroy
    @user_article_view.destroy
    respond_to do |format|
      format.html { redirect_to user_article_views_url, notice: 'User article view was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def comment
    unless session[:user_id]
      render :json {
        success: false,
        reason: "user not logged in"
      }
      return
    end
    comment_view = UserArticleView.new(:user_id => params[:user_id], :article_id => params[:article_id], :type => "comment", :data => params[:comment], :view_time => (Time.now.to_f * 1000).to_i)
    if comment_view.save
      render :json {
        success: true
      }
    else
      render: json {
        success: false
      }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_article_view
      @user_article_view = UserArticleView.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_article_view_params
      params[:user_article_view]
    end
end

v1/app/helpers/user_article_views_helper.rb
module UserArticleViewsHelper
end

v1/app/views/user_article_views/_form.html.erb
<%= form_for(@user_article_view) do |f| %>
  <% if @user_article_view.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_article_view.errors.count, "error") %> prohibited this user_article_view from being saved:</h2>

      <ul>
      <% @user_article_view.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

v1/app/views/user_article_views/edit.html.erb
<h1>Editing User Article View</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_article_view %> |
<%= link_to 'Back', user_article_views_path %>

v1/app/views/user_article_views/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Article Views</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_article_views.each do |user_article_view| %>
      <tr>
        <td><%= link_to 'Show', user_article_view %></td>
        <td><%= link_to 'Edit', edit_user_article_view_path(user_article_view) %></td>
        <td><%= link_to 'Destroy', user_article_view, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User article view', new_user_article_view_path %>

v1/app/views/user_article_views/new.html.erb
<h1>New User Article View</h1>

<%= render 'form' %>

<%= link_to 'Back', user_article_views_path %>

v1/app/views/user_article_views/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_article_view_path(@user_article_view) %> |
<%= link_to 'Back', user_article_views_path %>