v1/config/routes.rb
Rails.application.routes.draw do
  resources :user_article_views
  resources :bookmarks
  resources :summaries
  resources :users
  resources :articles

  root "home#index"

end

v1/app/models/summary.rb
class Summary < ActiveRecord::Base
end

v1/app/controllers/summaries_controller.rb
class SummariesController < ApplicationController
  before_action :set_summary, only: [:show, :edit, :update, :destroy]

  # GET /summaries
  # GET /summaries.json
  def index
    @summaries = Summary.all
  end

  # GET /summaries/1
  # GET /summaries/1.json
  def show
  end

  # GET /summaries/new
  def new
    @summary = Summary.new
  end

  # GET /summaries/1/edit
  def edit
  end

  # POST /summaries
  # POST /summaries.json
  def create
    @summary = Summary.new(summary_params)

    respond_to do |format|
      if @summary.save
        format.html { redirect_to @summary, notice: 'Summary was successfully created.' }
        format.json { render :show, status: :created, location: @summary }
      else
        format.html { render :new }
        format.json { render json: @summary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /summaries/1
  # PATCH/PUT /summaries/1.json
  def update
    respond_to do |format|
      if @summary.update(summary_params)
        format.html { redirect_to @summary, notice: 'Summary was successfully updated.' }
        format.json { render :show, status: :ok, location: @summary }
      else
        format.html { render :edit }
        format.json { render json: @summary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /summaries/1
  # DELETE /summaries/1.json
  def destroy
    @summary.destroy
    respond_to do |format|
      format.html { redirect_to summaries_url, notice: 'Summary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_summary
      @summary = Summary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def summary_params
      params[:summary]
    end
end

v1/app/helpers/summaries_helper.rb
module SummariesHelper
end

v1/app/views/summaries/_form.html.erb
<%= form_for(@summary) do |f| %>
  <% if @summary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@summary.errors.count, "error") %> prohibited this summary from being saved:</h2>

      <ul>
      <% @summary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

v1/app/views/summaries/edit.html.erb
<h1>Editing Summary</h1>

<%= render 'form' %>

<%= link_to 'Show', @summary %> |
<%= link_to 'Back', summaries_path %>

v1/app/views/summaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Summaries</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @summaries.each do |summary| %>
      <tr>
        <td><%= link_to 'Show', summary %></td>
        <td><%= link_to 'Edit', edit_summary_path(summary) %></td>
        <td><%= link_to 'Destroy', summary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Summary', new_summary_path %>

v1/app/views/summaries/new.html.erb
<h1>New Summary</h1>

<%= render 'form' %>

<%= link_to 'Back', summaries_path %>

v1/app/views/summaries/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_summary_path(@summary) %> |
<%= link_to 'Back', summaries_path %>